name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees:
  - Matheus-C-Martins

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Setup & Installation
        - Configuration
        - Deployment
        - API Usage
        - Contributing
        - Testing
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us answer
      placeholder: I'm trying to...

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What solutions have you already attempted?
      placeholder: I tried...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues
          required: true
